CREATE TABLE USERS (
    USER_ID     VARCHAR2(20)                    NOT NULL,
    CREATED_AT  DATE         DEFAULT SYSDATE    NOT NULL,
    PASSWORD    VARCHAR2(20)                    NOT NULL,
    NAME        VARCHAR2(20)                    NOT NULL,
    ROLE        VARCHAR2(20) DEFAULT 'USER'     NOT NULL,
    
    CONSTRAINT PK_USERS
        PRIMARY KEY (USER_ID),
        
    CONSTRAINT CK_USERS_ROLE
        CHECK (ROLE IN ('USER', 'ADMIN'))
);
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U000','PASS000','관리자','ADMIN');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U001','PASS001','유저1','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U002','PASS002','유저2','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U003','PASS003','유저3','USER');
