CREATE TABLE SESSIONS(
    SESSION_ID   VARCHAR2(20) NOT NULL,
    USER_ID      VARCHAR2(20) NOT NULL,
    SUMMARY      VARCHAR2(20) NOT NULL,
    STARTED_AT   DATE         DEFAULT SYSDATE,
    ENDED_AT     DATE         DEFAULT SYSDATE,
    
    CONSTRAINT PK_SESSIONS
        PRIMARY KEY (SESSION_ID),
        
    CONSTRAINT FK_SESSIONS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY, STARTED_AT, ENDED_AT)
VALUES ('S001','U001','RAG 테스트',SYSDATE - 1/24,SYSDATE - 1/24 + 5/1440);
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S002','U002','RAG DB설계');
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S003','U003','RAG 기술');