CREATE TABLE SESSIONS(
    SESSION_ID   VARCHAR2(20) NOT NULL,
    USER_ID      VARCHAR2(20) NOT NULL,
    SUMMARY      VARCHAR2(20) NOT NULL,
    STARTED_AT   DATE         DEFAULT SYSDATE,
    ENDED_AT     DATE         DEFAULT SYSDATE,
    
    CONSTRAINT PK_SESSIONS
        PRIMARY KEY (SESSION_ID),
        
    CONSTRAINT FK_SESSIONS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);