CREATE TABLE QUERY_LOGS(
    QUERY_ID    VARCHAR2(20)                    NOT NULL,
    SESSION_ID  VARCHAR2(20)                    NOT NULL,
    USER_ID     VARCHAR(20)                     NOT NULL,
    QUERY_TEXT  VARCHAR2(2000)                  NOT NULL,
    QUERY_AT    DATE            DEFAULT SYSDATE NOT NULL,
    PARAMETERS  VARCHAR2(2000),
    
    CONSTRAINT PK_QUERY_LOGS
        PRIMARY KEY (QUERY_ID),
        
    CONSTRAINT FK_QUERY_LOGS_SESSIONS
        FOREIGN KEY (SESSION_ID)
        REFERENCES SESSIONS (SESSION_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_QUERY_LOGS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);