CREATE TABLE RESPONSES (
    RESPONSE_ID     VARCHAR2(20)                 NOT NULL,
    QUERY_ID        VARCHAR2(20)                 NOT NULL,
    RESPONSE_TEXT   VARCHAR2(2000)               NOT NULL,
    RESPONSE_MODEL  VARCHAR2(20)                 NOT NULL,
    RESPONSE_DELAY  NUMBER,
    CREATED_AT      DATE         DEFAULT SYSDATE NOT NULL,
    PROMPT_TOKEN    NUMBER                       NOT NULL,
    COMPLETE_TOKEN  NUMBER                       NOT NULL,
    
    CONSTRAINT PK_RESPONSES
        PRIMARY KEY (RESPONSE_ID),
        
    CONSTRAINT FK_RESPONSES_QUERY_LOGS
        FOREIGN KEY (QUERY_ID)
        REFERENCES QUERY_LOGS (QUERY_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT CK_RESPONSES_PROMPT_TOKEN
        CHECK (PROMPT_TOKEN >= 0),
        
    CONSTRAINT CK_RESPONSES_COMPLETE_TOKEN
        CHECK ( COMPLETE_TOKEN >= 0 ),
        
    CONSTRAINT CK_RESPONSES_DELAY
        CHECK (RESPONSE_DELAY IS NULL OR RESPONSE_DELAY >= 0)
);
