CREATE TABLE FEEDBACKS(
    FEEDBACK_ID      VARCHAR2(20)                   NOT NULL,
    RESPONSE_ID      VARCHAR2(20)                   NOT NULL,
    USER_ID          VARCHAR2(20)                   NOT NULL,
    FEEDBACK_COMMENT VARCHAR2(200),
    GRADE            NUMBER                         NOT NULL,
    ERROR_TYPE       VARCHAR2(20),
    CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_FEEDBACKS
        PRIMARY KEY (FEEDBACK_ID),
        
    CONSTRAINT FK_FEEDBACKS_RESPONSES
        FOREIGN KEY (RESPONSE_ID)
        REFERENCES RESPONSES (RESPONSE_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT FK_FEEDBACKS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    
    CONSTRAINT CK_FEEDBACKS_GRADE
        CHECK (GRADE BETWEEN 1 AND 5)
);