CREATE TABLE DOCUMENTS (
    DOCUMENT_ID        VARCHAR2(20)                     NOT NULL,
    DOCUMENT_TITLE     VARCHAR2(50)                     NOT NULL,
    DOCUMENT_CATEGORY  VARCHAR2(20),
    WRITER_ID          VARCHAR2(20)                     NOT NULL,
    DOCUMENT_STATE     VARCHAR2(20)  DEFAULT 'ACTIVE'   NOT NULL,
    CREATED_AT         DATE          DEFAULT SYSDATE    NOT NULL,
    UPDATE_AT          DATE          DEFAULT SYSDATE    NOT NULL,

    CONSTRAINT PK_DOCUMENTS
        PRIMARY KEY (DOCUMENT_ID),

    CONSTRAINT FK_DOCUMENTS_USERS
        FOREIGN KEY (WRITER_ID)
        REFERENCES USERS (USER_ID),

    CONSTRAINT CK_DOCUMENTS_STATE
        CHECK (DOCUMENT_STATE IN ('ACTIVE', 'DISABLED'))
);