CREATE TABLE DOCUMENT_VERSIONS(
    DOCUMENT_VERSION_ID     VARCHAR2(20)                    NOT NULL,
    DOCUMENT_ID             VARCHAR2(20)                    NOT NULL,
    VERSION_NUM             NUMBER                          NOT NULL,
    CHANGED_RECORD          VARCHAR2(1000),
    CREATED_AT              DATE            DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_DOCUMENT_VERSIONS
        PRIMARY KEY (DOCUMENT_VERSION_ID),
        
    CONSTRAINT FK_DOC_VERSIONS_DOCUMENTS
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS (DOCUMENT_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT CK_DOC_VERSIONS_VER_NUM
        CHECK (VERSION_NUM >= 1)
);