CREATE TABLE CHUNKS(
    CHUNK_ID            VARCHAR2(20)    NOT NULL,
    DOCUMENT_VERSION_ID VARCHAR2(20)    NOT NULL,
    TOKEN_LENGTH        VARCHAR2(20)    NOT NULL,
    CHUNK_ORDER         NUMBER          NOT NULL,
    CHUNK_TEXT          VARCHAR2(4000)  NOT NULL,
    
   CONSTRAINT PK_CHUNKS
        PRIMARY KEY (CHUNK_ID),
    
    CONSTRAINT FK_CHUNKS_DOC_VERSIONS
        FOREIGN KEY (DOCUMENT_VERSION_ID)
        REFERENCES DOCUMENT_VERSIONS (DOCUMENT_VERSION_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT CK_CHUNKS_TOKEN_LENGTH
        CHECK (TOKEN_LENGTH >= 0),
    
    CONSTRAINT CK_CHUNKS_ORDER
        CHECK (CHUNK_ORDER >= 0)
);