CREATE TABLE EMBEDDING_MODELS(
    MODEL_ID        VARCHAR2(20)                NOT NULL,
    MODEL_NAME      VARCHAR2(20)                NOT NULL,
    DIMENSION       NUMBER                      NOT NULL,
    MODEL_VERSION   NUMBER                      NOT NULL,
    REGISTRATION    DATE        DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_EMBEDDING_MODELS
        PRIMARY KEY (MODEL_ID),
    
    CONSTRAINT CK_MODEL_VERSION
        CHECK(MODEL_VERSION >= 0)
);