CREATE TABLE EMBEDDING_REFERENCES(
    EMB_REF_ID      VARCHAR2(20)                NOT NULL,
    CHUNK_ID        VARCHAR2(20)                NOT NULL,
    MODEL_ID        VARCHAR2(20)                NOT NULL,
    VECTOR_ID       VARCHAR2(20)                NOT NULL,
    CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL,
    COLLECTION_NAME VARCHAR2(20)                NOT NULL,
    REEMBED_NEEDED  CHAR(1)     DEFAULT 'N',
    
    CONSTRAINT PK_EMBEDDING_REFERENCES
        PRIMARY KEY (EMB_REF_ID),
        
    CONSTRAINT FK_EMB_REFS_CHUNKS
        FOREIGN KEY (CHUNK_ID)
        REFERENCES CHUNKS (CHUNK_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_EMB_REFS_MODELS
        FOREIGN KEY (MODEL_ID)
        REFERENCES EMBEDDING_MODELS (MODEL_ID),
    
    CONSTRAINT CK_EMB_REFS_REEMBED
        CHECK (REEMBED_NEEDED IN ('N', 'Y'))
);