INSERT INTO DOCUMENTS(DOCUMENT_ID,DOCUMENT_TITlE,DOCUMENT_CATEGORY,
                      WRITER_ID,DOCUMENT_STATE,CREATED_AT,UPDATE_AT)
VALUES('D001','RAG 시스템 개요','AI','U000','ACTIVE',SYSDATE-3,SYSDATE-1);
INSERT INTO DOCUMENTS(DOCUMENT_ID,DOCUMENT_TITlE,DOCUMENT_CATEGORY,
                      WRITER_ID,DOCUMENT_STATE,CREATED_AT,UPDATE_AT)
VALUES('D002','Oracle DB 기초','DB','U000','ACTIVE',SYSDATE-13,SYSDATE-10);
INSERT INTO DOCUMENTS(DOCUMENT_ID,DOCUMENT_TITlE,DOCUMENT_CATEGORY,
                      WRITER_ID,DOCUMENT_STATE,CREATED_AT,UPDATE_AT)
VALUES('D003','RDBMS 개요','DB','U000','ACTIVE',SYSDATE-5,SYSDATE-2);

SELECT * FROM documents