INSERT INTO CHUNKS(CHUNK_ID,DOCUMENT_VERSION_ID,TOKEN_LENGTH,CHUNK_ORDER,CHUNK_TEXT)
VALUES('C001','DV001',120,1,'RAG 시스템은 검색과 생성 모델을 결합한 구조이다.');
INSERT INTO CHUNKS(CHUNK_ID,DOCUMENT_VERSION_ID,TOKEN_LENGTH,CHUNK_ORDER,CHUNK_TEXT)
VALUES('C002','DV001',95,2,'임베딩을 활용하여 관련 문서를 검색한 뒤, 답변을 생성한다.');
INSERT INTO CHUNKS(CHUNK_ID,DOCUMENT_VERSION_ID,TOKEN_LENGTH,CHUNK_ORDER,CHUNK_TEXT)
VALUES('C003','DV002',110,1,'Oracle Database는 관계형 데이터베이스 관리 시스템이다.');
SELECT * FROM CHUNKS;