INSERT INTO EMBEDDING_MODELS(MODEL_ID,MODEL_NAME,DIMENSION,MODEL_VERSION,REGISTRATION)
VALUES('M001','text-emd-ada-002',1536,1.0,SYSDATE-10);
INSERT INTO EMBEDDING_MODELS(MODEL_ID,MODEL_NAME,DIMENSION,MODEL_VERSION,REGISTRATION)
VALUES('M002','all-MiniLM-L6-v2',384,1.0,SYSDATE-5);
INSERT INTO EMBEDDING_MODELS(MODEL_ID,MODEL_NAME,DIMENSION,MODEL_VERSION,REGISTRATION)
VALUES('M003','BGE-M3',1024,1.0,SYSDATE);

SELECT * FROM EMBEDDING_MODELS