INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY, STARTED_AT, ENDED_AT)
VALUES ('S001','U001','RAG 테스트',SYSDATE - 1/24,SYSDATE - 1/24 + 5/1440);
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S002','U002','RAG DB설계');
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S003','U003','RAG 기술');

SELECT * FROM SESSIONS