INSERT INTO EMBEDDING_REFERENCES(EMB_REF_ID,CHUNK_ID,MODEL_ID,VECTOR_ID,CREATED_AT,COLLECTION_NAME,REEMBED_NEEDED)
VALUES('E001','C001','M001','vec-001',SYSDATE-1,'rag_collection','N');
INSERT INTO EMBEDDING_REFERENCES(EMB_REF_ID,CHUNK_ID,MODEL_ID,VECTOR_ID,CREATED_AT,COLLECTION_NAME,REEMBED_NEEDED)
VALUES('E002','C002','M001','vec-002',SYSDATE-3,'rag_collection','N');
INSERT INTO EMBEDDING_REFERENCES(EMB_REF_ID,CHUNK_ID,MODEL_ID,VECTOR_ID,CREATED_AT,COLLECTION_NAME,REEMBED_NEEDED)
VALUES('E003','C003','M001','vec-003',SYSDATE-5,'rag_collection','Y');

SELECT * FROM EMBEDDING_REFERENCES