INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U000','PASS000','관리자','ADMIN');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U001','PASS001','유저1','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U002','PASS002','유저2','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U003','PASS003','유저3','USER');
