INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S001','U001','RAG 테스트');
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S002','U002','RAG DB설계');
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S003','U003','RAG 기술');