INSERT INTO FEEDBACKS (
    FEEDBACK_ID, RESPONSE_ID, USER_ID,
    FEEDBACK_COMMENT, GRADE, ERROR_TYPE, CREATED_AT) 
VALUES (
    'F001', 'R001', 'U001',
    '설명이 이해하기 쉬움', 5, NULL, SYSDATE-2
);
INSERT INTO FEEDBACKS (
    FEEDBACK_ID, RESPONSE_ID, USER_ID,
    FEEDBACK_COMMENT, GRADE, ERROR_TYPE, CREATED_AT) 
VALUES (
    'F002', 'R002', 'U002',
    '개념이 좀 부족한듯', 3, NULL, SYSDATE-2
);
INSERT INTO FEEDBACKS (
    FEEDBACK_ID, RESPONSE_ID, USER_ID,
    FEEDBACK_COMMENT, GRADE, ERROR_TYPE, CREATED_AT) 
VALUES (
    'F003', 'R003', 'U003',
    '논리가 완벽하다', 5, NULL, SYSDATE-2
);