INSERT INTO DOCUMENT_VERSIONS(DOCUMENT_VERSION_ID,DOCUMENT_ID,VERSION_NUM
                            ,CHANGED_RECORD,CREATED_AT)
VALUES('DV001','D001','1','최초 작성',SYSDATE-2);
INSERT INTO DOCUMENT_VERSIONS(DOCUMENT_VERSION_ID,DOCUMENT_ID,VERSION_NUM
                            ,CHANGED_RECORD,CREATED_AT)
VALUES('DV002','D001','1.01','코드 수정',SYSDATE-1);
INSERT INTO DOCUMENT_VERSIONS(DOCUMENT_VERSION_ID,DOCUMENT_ID,VERSION_NUM
                            ,CHANGED_RECORD,CREATED_AT)
VALUES('DV003','D001','1.11','문서 내용 재구성',SYSDATE);