INSERT INTO QUERY_LOGS(QUERY_ID,SESSION_ID,USER_ID,QUERY_TEXT,QUERY_AT,PARAMETERS)
VALUES('Q001','S001','U001','RAG 시스템에 대해 설명해줘',SYSDATE-2,'top_k : 3');
INSERT INTO QUERY_LOGS(QUERY_ID,SESSION_ID,USER_ID,QUERY_TEXT,QUERY_AT,PARAMETERS)
VALUES('Q002','S002','U002','VECTOR DB란?',SYSDATE-1,'top_k : 3');
INSERT INTO QUERY_LOGS(QUERY_ID,SESSION_ID,USER_ID,QUERY_TEXT,QUERY_AT,PARAMETERS)
VALUES('Q003','S003','U003','RAG 시스템의 장점에 대해 설명해줘',SYSDATE,'top_k : 3');

SELECT * FROM QUERY_LOGS;