INSERT INTO RESPONSES(RESPONSE_ID,QUERY_ID,RESPONSE_TEXT,RESPONSE_MODEL
                    ,RESPONSE_DELAY,CREATED_AT,PROMPT_TOKEN,COMPLETE_TOKEN)
VALUES  ('R001','Q001','RAG는 검색과 생성 모델의 결합한 기술입니다.','gpt-4o-mini',1200,SYSDATE-2,120,10);
INSERT INTO RESPONSES(RESPONSE_ID,QUERY_ID,RESPONSE_TEXT,RESPONSE_MODEL
                    ,RESPONSE_DELAY,CREATED_AT,PROMPT_TOKEN,COMPLETE_TOKEN)
VALUES  ('R002','Q002','VECTOR DB는 벡터임베딩을 저장하는 데이터베이스입니다. .','gpt-4o-mini',1200,SYSDATE-2,120,10);
INSERT INTO RESPONSES(RESPONSE_ID,QUERY_ID,RESPONSE_TEXT,RESPONSE_MODEL
                    ,RESPONSE_DELAY,CREATED_AT,PROMPT_TOKEN,COMPLETE_TOKEN)
VALUES  ('R003','Q003','RAG 기술은 LLM 답변의 할루미네이션 현상을 방지할 수 있습니다.','gpt-4o-mini',1200,SYSDATE-2,120,10);