CREATE TABLE USERS (
    USER_ID     VARCHAR2(20)                    NOT NULL,
    CREATED_AT  DATE         DEFAULT SYSDATE    NOT NULL,
    PASSWORD    VARCHAR2(20)                    NOT NULL,
    NAME        VARCHAR2(20)                    NOT NULL,
    ROLE        VARCHAR2(20) DEFAULT 'USER'     NOT NULL,
    
    CONSTRAINT PK_USERS
        PRIMARY KEY (USER_ID),
        
    CONSTRAINT CK_USERS_ROLE
        CHECK (ROLE IN ('USER', 'ADMIN'))
);
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U000','PASS000','관리자','ADMIN');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U001','PASS001','유저1','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U002','PASS002','유저2','USER');
INSERT INTO USERS(USER_ID, PASSWORD, NAME,ROLE)
VALUES ('U003','PASS003','유저3','USER');
CREATE TABLE SESSIONS(
    SESSION_ID   VARCHAR2(20) NOT NULL,
    USER_ID      VARCHAR2(20) NOT NULL,
    SUMMARY      VARCHAR2(20) NOT NULL,
    STARTED_AT   DATE         DEFAULT SYSDATE,
    ENDED_AT     DATE         DEFAULT SYSDATE,
    
    CONSTRAINT PK_SESSIONS
        PRIMARY KEY (SESSION_ID),
        
    CONSTRAINT FK_SESSIONS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY, STARTED_AT, ENDED_AT)
VALUES ('S001','U001','RAG 테스트',SYSDATE - 1/24,SYSDATE - 1/24 + 5/1440);
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S002','U002','RAG DB설계');
INSERT INTO SESSIONS(SESSION_ID, USER_ID, SUMMARY)
VALUES ('S003','U003','RAG 기술');

CREATE TABLE QUERY_LOGS(
    QUERY_ID    VARCHAR2(20)                    NOT NULL,
    SESSION_ID  VARCHAR2(20)                    NOT NULL,
    USER_ID     VARCHAR(20)                     NOT NULL,
    QUERY_TEXT  VARCHAR2(2000)                  NOT NULL,
    QUERY_AT    DATE            DEFAULT SYSDATE NOT NULL,
    PARAMETERS  VARCHAR2(2000),
    
    CONSTRAINT PK_QUERY_LOGS
        PRIMARY KEY (QUERY_ID),
        
    CONSTRAINT FK_QUERY_LOGS_SESSIONS
        FOREIGN KEY (SESSION_ID)
        REFERENCES SESSIONS (SESSION_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_QUERY_LOGS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);
INSERT INTO DOCUMENTS (
    DOCUMENT_ID, DOCUMENT_TITLE, DOCUMENT_CATEGORY,
    WRITER_ID, DOCUMENT_STATE, CREATED_AT, UPDATE_AT
)
VALUES (
    'D001','RAG 시스템 개요','AI',
    'U001','ACTIVE',SYSDATE - 3,SYSDATE - 1
);
INSERT INTO DOCUMENTS (
    DOCUMENT_ID, DOCUMENT_TITLE, DOCUMENT_CATEGORY,
    WRITER_ID, DOCUMENT_STATE, CREATED_AT, UPDATE_AT
) 
VALUES (
    'D002', 'Oracle DB 기초', 'DB',
    'U002', 'ACTIVE', SYSDATE - 5, SYSDATE - 2
);

CREATE TABLE RESPONSES (
    RESPONSE_ID     VARCHAR2(20)                 NOT NULL,
    QUERY_ID        VARCHAR2(20)                 NOT NULL,
    RESPONSE_TEXT   VARCHAR2(2000)               NOT NULL,
    RESPONSE_MODEL  VARCHAR2(20)                 NOT NULL,
    RESPONSE_DELAY  NUMBER,
    CREATED_AT      DATE         DEFAULT SYSDATE NOT NULL,
    PROMPT_TOKEN    NUMBER                       NOT NULL,
    COMPLETE_TOKEN  NUMBER                       NOT NULL,
    
    CONSTRAINT PK_RESPONSES
        PRIMARY KEY (RESPONSE_ID),
        
    CONSTRAINT FK_RESPONSES_QUERY_LOGS
        FOREIGN KEY (QUERY_ID)
        REFERENCES QUERY_LOGS (QUERY_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT CK_RESPONSES_PROMPT_TOKEN
        CHECK (PROMPT_TOKEN >= 0),
        
    CONSTRAINT CK_RESPONSES_COMPLETE_TOKEN
        CHECK ( COMPLETE_TOKEN >= 0 ),
        
    CONSTRAINT CK_RESPONSES_DELAY
        CHECK (RESPONSE_DELAY IS NULL OR RESPONSE_DELAY >= 0)
);
INSERT INTO DOCUMENT_VERSIONS (
    DOCUMENT_VERSION_ID, DOCUMENT_ID, VERSION_NUM, CHANGED_RECORD, CREATED_AT
)
VALUES (
    'DV001','D001',1,'최초 작성',SYSDATE - 3
);

INSERT INTO DOCUMENT_VERSIONS (
    DOCUMENT_VERSION_ID, DOCUMENT_ID, VERSION_NUM,
    CHANGED_RECORD, CREATED_AT
)
VALUES (
    'DV002','D002',1,'최초 작성',SYSDATE - 5
);

CREATE TABLE FEEDBACKS(
    FEEDBACK_ID      VARCHAR2(20)                   NOT NULL,
    RESPONSE_ID      VARCHAR2(20)                   NOT NULL,
    USER_ID          VARCHAR2(20)                   NOT NULL,
    FEEDBACK_COMMENT VARCHAR2(200),
    GRADE            NUMBER                         NOT NULL,
    ERROR_TYPE       VARCHAR2(20),
    CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_FEEDBACKS
        PRIMARY KEY (FEEDBACK_ID),
        
    CONSTRAINT FK_FEEDBACKS_RESPONSES
        FOREIGN KEY (RESPONSE_ID)
        REFERENCES RESPONSES (RESPONSE_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT FK_FEEDBACKS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    
    CONSTRAINT CK_FEEDBACKS_GRADE
        CHECK (GRADE BETWEEN 1 AND 5)
);
INSERT INTO FEEDBACKS(FEEDBACK_ID,RESPONSE_ID,USER_ID)
CREATE TABLE DOCUMENTS(
    DOCUMENT_ID         VARCHAR2(20)                    NOT NULL,
    DOCUMENT_TITLE      VARCHAR2(50)                    NOT NULL,
    DOCUMENT_CATEGORY   VARCHAR2(20),
    WRITER_ID           VARCHAR2(20)                    NOT NULL,
    DOCUMENT_STATE      VARCHAR2(20) DEFAULT 'ACTIVE'   NOT NULL,
    CREATED_AT          DATE         DEFAULT SYSDATE    NOT NULL,
    UPDATE_AT           DATE         DEFAULT SYSDATE    NOT NULL,
    
    CONSTRAINT PK_DOCUMENTS
        PRIMARY KEY (DOCUMENT_ID),
        
    CONSTRAINT FK_DOCUMENTS_USERS
        FOREIGN KEY (WRITER_ID)
        REFERENCES USERS (USER_ID),
        
    CONSTRAINT CK_DOCUMENTS_STATE
        CHECK (DOCUMENT_STATE IN ('ACTIVE', 'DISABLED'))
);
CREATE TABLE DOCUMENT_VERSIONS(
    DOCUMENT_VERSION_ID     VARCHAR2(20)                    NOT NULL,
    DOCUMENT_ID             VARCHAR2(20)                    NOT NULL,
    VERSION_NUM             NUMBER                          NOT NULL,
    CHANGED_RECORD          VARCHAR2(1000),
    CREATED_AT              DATE            DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_DOCUMENT_VERSIONS
        PRIMARY KEY (DOCUMENT_VERSION_ID),
        
    CONSTRAINT FK_DOC_VERSIONS_DOCUMENTS
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS (DOCUMENT_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT CK_DOC_VERSIONS_VER_NUM
        CHECK (VERSION_NUM >= 1)
);
CREATE TABLE CHUNKS(
    CHUNK_ID            VARCHAR2(20)    NOT NULL,
    DOCUMENT_VERSION_ID VARCHAR2(20)    NOT NULL,
    TOKEN_LENGTH        VARCHAR2(20)    NOT NULL,
    CHUNK_ORDER         NUMBER          NOT NULL,
    CHUNK_TEXT          VARCHAR2(4000)  NOT NULL,
    
   CONSTRAINT PK_CHUNKS
        PRIMARY KEY (CHUNK_ID),
    
    CONSTRAINT FK_CHUNKS_DOC_VERSIONS
        FOREIGN KEY (DOCUMENT_VERSION_ID)
        REFERENCES DOCUMENT_VERSIONS (DOCUMENT_VERSION_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT CK_CHUNKS_TOKEN_LENGTH
        CHECK (TOKEN_LENGTH >= 0),
    
    CONSTRAINT CK_CHUNKS_ORDER
        CHECK (CHUNK_ORDER >= 0)
);
CREATE TABLE EMBEDDING_MODELS(
    MODEL_ID        VARCHAR2(20)                NOT NULL,
    MODEL_NAME      VARCHAR2(20)                NOT NULL,
    DIMENSION       NUMBER                      NOT NULL,
    MODEL_VERSION   NUMBER                      NOT NULL,
    REGISTRATION    DATE        DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_EMBEDDING_MODELS
        PRIMARY KEY (MODEL_ID),
    
    CONSTRAINT CK_MODEL_VERSION
        CHECK(MODEL_VERSION >= 0)
);
CREATE TABLE EMBEDDING_REFERENCES(
    EMB_REF_ID      VARCHAR2(20)                NOT NULL,
    CHUNK_ID        VARCHAR2(20)                NOT NULL,
    MODEL_ID        VARCHAR2(20)                NOT NULL,
    VECTOR_ID       VARCHAR2(20)                NOT NULL,
    CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL,
    COLLECTION_NAME VARCHAR2(20)                NOT NULL,
    REEMBED_NEEDED  CHAR(1)     DEFAULT 'N',
    
    CONSTRAINT PK_EMBEDDING_REFERENCES
        PRIMARY KEY (EMB_REF_ID),
        
    CONSTRAINT FK_EMB_REFS_CHUNKS
        FOREIGN KEY (CHUNK_ID)
        REFERENCES CHUNKS (CHUNK_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_EMB_REFS_MODELS
        FOREIGN KEY (MODEL_ID)
        REFERENCES EMBEDDING_MODELS (MODEL_ID),
    
    CONSTRAINT CK_EMB_REFS_REEMBED
        CHECK (REEMBED_NEEDED IN ('N', 'Y'))
);
CREATE TABLE SEARCH_RESULT(
    RESULT_ID       VARCHAR2(20)                NOT NULL,
    QUERY_ID        VARCHAR2(20)                NOT NULL,
    EMB_REF_ID      VARCHAR2(20)                NOT NULL,
    RESULT_RANK     NUMBER                      NOT NULL,
    CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL,
    SIMILARITY      NUMBER                      NOT NULL,
    
    CONSTRAINT PK_SEARCH_RESULT
        PRIMARY KEY (RESULT_ID),
        
    CONSTRAINT FK_SEARCH_RESULT_QUERY_LOGS
        FOREIGN KEY (QUERY_ID)
        REFERENCES QUERY_LOGS (QUERY_ID)
        ON DELETE CASCADE,
    
    CONSTRAINT FK_SEARCH_RESULT_EMB_REFS
        FOREIGN KEY (EMB_REF_ID)
        REFERENCES EMBEDDING_REFERENCES (EMB_REF_ID),
    
    CONSTRAINT CK_SEARCH_RESULT_RANK
        CHECK (RESULT_RANK >= 1),
    
    CONSTRAINT CK_SEARCH_RESULT_SIMILARITY
        CHECK (SIMILARITY >= 0 AND SIMILARITY <= 1)
);


DROP TABLE USERS
DROP TABLE QUERY_LOGS
DROP TABLE RESPONSES
DROP TABLE SESSIONS
DROP TABLE FEEDBACKS
DROP TABLE DOCUMENTS
DROP TABLE DOCUMENT_VERSIONS
DROP TABLE CHUNKS
DROP TABLE EMBEDDING_REFERENCES
DROP TABLE EMBEDDING_MODELS
DROP TABLE SEARCH_RESULT